name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
jobs:
  bare_run:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      -
        run: |
          composer install
          php vendor/bin/monorepo-builder release ${{ inputs.version }}
